import { BookOpen, FileText, Video, Presentation } from 'lucide-react';
export const navLinks = [
  { name: 'Home', href: '/' },
  { name: 'Lessons', href: '/lessons' },
  { name: 'Resources', href: '/resources' },
  { name: 'Blog', href: '/blog' },
];
export const curriculum = {
  grade9: {
    title: '9th Grade Curriculum',
    lessons: [
      {
        id: 'g9-1',
        title: 'Introduction to Biomedical Tech',
        description: 'Foundations of medical device technology and its role in modern healthcare.',
        duration: '45 mins',
        tags: ['Foundations', 'Safety'],
        image: 'https://images.unsplash.com/photo-1576091160550-2173bdb999ef?auto=format&fit=crop&q=80&w=800',
      },
      {
        id: 'g9-2',
        title: 'Basic Anatomy for Engineers',
        description: 'Understanding human systems from a mechanical and electrical perspective.',
        duration: '60 mins',
        tags: ['Anatomy', 'Biology'],
        image: 'https://images.unsplash.com/photo-1530210124550-912dc1381cb8?auto=format&fit=crop&q=80&w=800',
      },
    ],
  },
  grade10: {
    title: '10th Grade Curriculum',
    lessons: [
      {
        id: 'g10-1',
        title: 'Sensors & Transducers',
        description: 'Exploring how physical biological signals are converted into electrical data.',
        duration: '55 mins',
        tags: ['Electronics', 'Signal'],
        image: 'https://images.unsplash.com/photo-1555664424-778a1e5e1b48?auto=format&fit=crop&q=80&w=800',
      },
      {
        id: 'g10-2',
        title: 'Medical Imaging Fundamentals',
        description: 'Introduction to X-Ray, MRI, and Ultrasound technology principles.',
        duration: '75 mins',
        tags: ['Imaging', 'Radiology'],
        image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
      },
    ],
  },
  coreFields: {
    title: 'Core Field Lessons',
    lessons: [
      {
        id: 'core-1',
        title: 'Clinical Engineering',
        description: 'Management and maintenance of medical equipment in hospital settings.',
        duration: '90 mins',
        tags: ['Maintenance', 'Management'],
        image: 'https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&q=80&w=800',
      },
      {
        id: 'core-2',
        title: 'Bio-Signal Processing',
        description: 'Advanced techniques for analyzing ECG, EEG, and EMG signals.',
        duration: '120 mins',
        tags: ['Data Science', 'Signal'],
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
      },
    ],
  },
};
export const resources = [
  {
    id: 'res-1',
    type: 'PDF',
    title: 'Safety Standards Handbook',
    description: 'Essential electrical safety guidelines for medical devices.',
    icon: FileText,
    category: 'Safety',
    fileSize: '2.4 MB',
  },
  {
    id: 'res-2',
    type: 'Presentation',
    title: 'The Future of Prosthetics',
    description: 'Visual slides covering robotic limbs and neural interfaces.',
    icon: Presentation,
    category: 'Innovation',
    fileSize: '15.8 MB',
  },
  {
    id: 'res-3',
    type: 'Video',
    title: 'Hemodialysis Machine Walkthrough',
    description: 'Step-by-step breakdown of blood purification systems.',
    icon: Video,
    category: 'Equipment',
    duration: '12:45',
  },
  {
    id: 'res-4',
    type: 'PDF',
    title: 'Maintenance Logbook Template',
    description: 'Ready-to-use template for medical equipment tracking.',
    icon: FileText,
    category: 'Equipment',
    fileSize: '0.8 MB',
  },
];
export const blogPosts = [
  {
    id: 'post-1',
    title: 'The Rise of AI in Diagnostic Imaging',
    excerpt: 'How machine learning algorithms are revolutionizing the way radiologists detect early-stage pathologies.',
    date: 'Oct 24, 2023',
    readTime: '6 min read',
    author: 'Dr. Sarah Chen',
    category: 'AI & Imaging',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800',
    featured: true,
  },
  {
    id: 'post-2',
    title: 'Wearable Tech: Beyond Heart Rate Tracking',
    excerpt: 'Exploring the next generation of continuous glucose monitoring and sweat analysis patches.',
    date: 'Oct 18, 2023',
    readTime: '4 min read',
    author: 'James Wilson',
    category: 'Wearables',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800',
    featured: false,
  },
  {
    id: 'post-3',
    title: '3D Printing in Surgical Planning',
    excerpt: 'How patient-specific anatomical models are reducing time in the operating room.',
    date: 'Oct 12, 2023',
    readTime: '8 min read',
    author: 'Elena Rodriguez',
    category: 'Surgery',
    image: 'https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&q=80&w=800',
    featured: false,
  },
];